### ISSUE TITLE
M-x spot4e-authorize is missing

### ISSUE THREAD

**Issue by RidaAyed** [chiply/spot4e#11] opened 2019-06-29 14:09 UTC
Hi

After the taking the steps below, I'm still missing spot4e. E.g. `M-x spot4e-authorize` is
not available nor any other spot4e command.

Cloned this repo:

    git clone git@github.com:chiply/spot4e.git ~/.emacs.d/private/spotify

Load the path:

    (add-to-list 'load-path "/home/ra/.emacs.d/private/spotify/spot4e.el")

**Comment by chiply** [comment] 2019-07-01 22:57
Hi Rida - thank you for your post!  looking into this now :-)

**Comment by chiply** [comment] 2019-07-01 23:11
hmmm not sure what the issue is at first glance.  Can you try going into the spot4e file, doing M-x eval-buffer and then try M-x spot4e-authorize?

**Comment by chiply** [comment] 2019-08-26 17:23
Going to close this issue.  I recommend changing the string in your load path to reflect the directory, not the file.  it looks like you're point to spot4e.el when you should be pointing to the directory, spot4e.

**Closed as completed by chiply** 2019-08-26 17:23 UTC
